controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    jax_controller:
      type: joint_trajectory_controller/JointTrajectoryController

jax_controller:
  ros__parameters:
    joints:
      - front_right_hip_joint
      - front_right_thigh_joint
      - front_right_knee_joint
      - front_left_hip_joint
      - front_left_thigh_joint
      - front_left_knee_joint
      - rear_right_hip_joint
      - rear_right_thigh_joint
      - rear_right_knee_joint
      - rear_left_hip_joint
      - rear_left_thigh_joint
      - rear_left_knee_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    # This allows the robot to move smoothly between points
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
